{{- if and (ne (.Values.database.type | lower) "h2") (not .Values.database.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metabase.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metabase.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  host: {{ .Values.database.host | quote }}
  port: {{ .Values.database.port | quote }}
{{- end }}
